---
- hosts: webserver
  become: yes --> it's used as sudop
  tasks:

    - name: update
      apt: update_cache=yes

    - name: install apache2
      apt: name=apache2 state=latest

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present

    - name: enabled proxy
      apache2_module: name=proxy state=present

    - name: enabled proxy_http
      apache2_module: name=proxy_http state=present

    - name: enabled ssl
      apache2_module: name=ssl state=present

    - name: enabled
~
